### ISSUE TITLE
Url password method causes failure when password includes disallowed url characters

### ISSUE THREAD

**Issue by lBowlin** [niwinz/django-redis#114]
Using a password in the url that does not have valid url characters (such as the forward slashes used in Azure Redis Cache) causes a failure when it runs urlparse. I have reported this issue to Redis-py as well, but in the meantime deprecating the old "PASSWORD=" method would break compatibility with Azure Redis Cache.

**Comment by niwibe** [comment]
Would be awesome have a url example that causes that regression. Maybe we can implement temporary workaround for it.

**Comment by lBowlin** [comment]
Sorry, forgot to paste this snippet in.

Cloud services that required passwords such as "iAITMl7lD127c/VZEl0OZl8qviaXHIoKekaJjP1J1HI=" can contain a variety of characters including forward slashes which are invalid in a url string.

Link to bug report on redis-py: https://github.com/andymccurdy/redis-py/issues/579

**Comment by niwibe** [comment]
Thank you @lBowlin 
As fast workaround, you can use the 3.7.x branch that is also stable and not uses redis-py url notation.

**Comment by lBowlin** [comment]
Great thank you for the info. I will update when I hear back from redis-py

**Comment by Koed00** [comment]
Looks like it's fixed at their end andymccurdy/redis-py/pull/586

**Comment by niwinz** [comment]
I will keep this issue open until the new release of redis-py is out ;)

**Comment by niwinz** [comment]
This seems already merged and new release issued. So this can be considered closed.
