### ISSUE TITLE
3.8.4 breaks Python 2.6 compatibility.

### ISSUE THREAD

**Issue by BertrandBordage** [niwinz/django-redis#132]
Because [importlib is used in util.py](https://github.com/niwinz/django-redis/blob/3.8.4/django_redis/util.py) since django-redis 3.8.4, python 2.6 (supported by Django 1.4, 1.5 & 1.6) can’t be used. Since django-redis 3.8.x is supposed to support these 3 versions of Django, this is a bug.

**Comment by niwinz** [comment]
Hi @BertrandBordage djangor-redis 3.8.x has support for django 1.4+ but it not implies have support for pyhon 2.6.

In the documentation, it is explicitly mentioned that python 2.7.x, 3.3.x and 3.4.x are supported.
Lamentably I do not have plans for support python 2.6 myself. If you want provide a reasonable and not very intrusive patch for fixing compatibility with python 2.6 I'll accept it.

**Comment by BertrandBordage** [comment]
Hi @niwinz!

Right, I didn’t see it  in the docs because it wasn’t listed in the Requirements section.

No, I don’t really care about Python 2.6. I’m only reporting this because the test suite of django cachalot uses it along with django-redis. I simply downgraded it, that’s enough for me.

Thanks for you time!

**Comment by niwinz** [comment]
Thanks to you for using it and reporting bugs!
