### ISSUE TITLE
Add support for alternative serializers (other than pickle)

### ISSUE THREAD

**Issue by jdufresne** [niwinz/django-redis#133]
I'm integrating django-redis into an application that shares a browser session across multiple applications. This session must be readable by applications written in languages other than Python.

When integrating django-redis, I noticed that all data sent to the cache server is first serialized using pickle. While this makes sense for Python only applications, it isn't very friendly for non-Python applications.

Would you be open to adding support for alternative serializers in the `DefaultClient` class? The default would continue to be pickle, but by adding a `JSONClient` (or whatever name) the user could serialize the data to a format that is more language agnostic.

If you're open to this idea I don't mind doing the work. I'm motivated as I'd need to do this anyway for my project. Care would be taken to factor out the common client code so only the serializing functions would be different.

This would be similar to how Django's session engine has support for multiple serializers: <https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-SESSION_SERIALIZER>

Thanks.

**Comment by niwinz** [comment]
hi @jdufresne!

Seems like a very great Idea, something like serializer support in sessions is very welcome.

**Comment by uditagarwal** [comment]
This is just what I was looking for :+1: 

I'd be willing to contribute if there's need for other Serialization too.

**Comment by uditagarwal** [comment]
https://github.com/uditagarwal/django-redis/commit/f34eee064a0e61b376f22af2dbe8c9dff61fc497
