### ISSUE TITLE
delete_pattern uses keys instead of iter_keys

### ISSUE THREAD

**Issue by lenzenmi** [niwinz/django-redis#141]
Is there any reason we couldn't change this to use a loop with iter_keys instead, or better yet, a custom lua script?

If there are a lot of keys in redis (even if they don't match your pattern) redis scans through each of them to generate the list to return. This can be quite slow, which is why the iter_keys method was introduced.

I'd be willing to take a crack at it, but I wanted to see if there was a deeper reasoning behind using the keys command, such as backwards compatability.

```python
def delete_pattern(self, pattern, version=None, client=None):
    """
    Remove all keys matching pattern.
    """
    if client is None:
    client = self.get_client(write=True)
    pattern = self.make_key(pattern, version=version)
    try:
        keys = client.keys(pattern)
        if keys:
            return client.delete(*keys)
        except _main_exceptions as e:
            raise ConnectionInterrupted(connection=client, parent=e)
```

**Comment by niwinz** [comment]
As far as I know, the keys is used because iter_keys is introduced later that delete_pattern...

You are right, seems that iter_keys is a better approach for delete_pattern :D

**Comment by lenzenmi** [comment]
Since you responded so quick, I went ahead and made a pull request. The tests are passing for me.
