### ISSUE TITLE
Documentation: mention a link to the django cache framework?

### ISSUE THREAD

**Issue by CrazyPython** [niwinz/django-redis#144]
https://docs.djangoproject.com/en/1.8/topics/cache/#basic-usage
For those not informed about basic interface.

**Comment by niwinz** [comment]
I'm not clearly understand your question, sorry.

**Comment by CrazyPython** [comment]
Show a link to the [django cache framework](https://docs.djangoproject.com/en/1.8/topics/cache/#basic-usage) in the documentation.

**Comment by niwinz** [comment]
Seems to be irrelevant or I'm clearly don't understand this issue.
