### ISSUE TITLE
Support for django-debug-toolbar

### ISSUE THREAD

**Issue by NotSqrt** [niwinz/django-redis#146]
Hello !

As of django-redis 3.7.2, there was no support for django-debug-toolbar.
When using the panel ``debug_toolbar.panels.cache.CachePanel``, it stays empty.

Is it supported now ?
If not, what would it take ?

Thanks !

**Comment by niwinz** [comment]
The django-redis is a pretty standard django cache backend, so if django-debug-toolbar does not work, so it seems a django-debug-toolbar problem.

I have seen a source code of the debug-toolbar related to the cache panel and I haven't seen any strange code that implies the not working situation with django-redis.

**Comment by NotSqrt** [comment]
It seems django-debug-toolbar >= 1.3 fixes that for django >= 1.7.
And obviously, if using the raw redis client, it won't report anything.

So everything is working as intended !
