### ISSUE TITLE
# of connections created by the connection pool keeps reading 0

### ISSUE THREAD

**Issue by ryanisnan** [niwinz/django-redis#160]
Running a Heroku app w/ Redis Green and RQ (with django-rq); everything's working fine. I was interested in using django-redis for connection pooling.

However, when I inspect the # of connections created in the pool via `get_redis_connection('redis').connection_pool._created_connections`, it consistently returns 0, despite my queues successfully processing jobs. Any thoughts?

**Comment by ryanisnan** [comment]
Here's the config for my 'redis' entry in django's `CACHES` setting.

    'redis': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,  # Taken from os.environ
        'OPTIONS': {
            'CONNECTION_POOL_KWARGS': {'max_connections': 100}
        }
    }

RQ is working fine with this configuration, which gives me confidence in the ability to connect to the redis cache.

    RQ_QUEUES = {
        'low': {
            'USE_REDIS_CACHE': 'redis',
        },
        'high': {
            'USE_REDIS_CACHE': 'redis',
        },
    }

What gives?

**Comment by niwinz** [comment]
Sincerelly I don't know how rq works so I can't help on it. Seems that it is not using it.

**Comment by niwinz** [comment]
I have tested it and if you are simply sets a key, the counter increases:

```pyshell
>>> from django.core.cache import caches
>>> from django_redis import get_redis_connection
>>> get_redis_connection("default").connection_pool._created_connections
0
>>> caches["default"].set("foo", "bar")
True
>>> get_redis_connection("default").connection_pool._created_connections
1
```

**Comment by ryanisnan** [comment]
I've noted that the # of connections created per minute does not have seemed to decrease since adding django-redis to the project.

![image](https://cloud.githubusercontent.com/assets/504281/9642942/d1c8308e-5173-11e5-8b6a-9ddfa25be3bf.png)

The lib that I use to integrate with rq is django-rq (https://github.com/ui/django-rq), and it has explicit support for django-redis for this use-case. Perhaps it's an issue with that lib?

**Comment by niwinz** [comment]
Maybe, you are not the first that has problems with that library. Seems it not manages well the resource management and not closes the connection. django-redis can't do anything because the library surelly access directly to the redis connection, so django-redis only serves as configuration loader...

I strongly recommed use rabbitmq (instead of redis), and maybe celery. Redis is not the best tool for... queue. I had a great a mount of cases of task losses and other strange behavior when using redis as message broker.

**Comment by ryanisnan** [comment]
I believe my initial line of reasoning to be slightly incorrect, as I was checking the connection pool while SSH'd into a heroku box. The connection pools themselves however, would be confined to each dyno instance that I have. N machines = N connection pools (assuming each machine does not go over the maximum number of connections per pool).

Still, I have no reason to suspect that any meaningful connection-pooling is happening. I've brought this issue up on django-rq, where I will look for any further info as to why this is the case.

Side note: Regarding rabbitmq/celery, personally I have had much greater success with rq and thus far it's performed exceedingly well. We'll see how difficult this connection pooling is to sort out!

**Comment by niwinz** [comment]
Good look and let me know If I can help in any thing ;)

**Comment by selwin** [comment]
Hello @niwinz! I'm the author of `django-rq` and am wondering if I can get your help debugging this problem.

The code to get Redis connection is [here](https://github.com/ryanisnan/django-rq/blob/master/django_rq/queues.py#L57), from lines 57 until 86. `get_redis_connection` from `django-redis` is used to return the Redis connection. However @ryanisnan reported no success with this method so I was wondering if we're using this method properly.

**Comment by niwinz** [comment]
hi @selwin It is everything ok in your code, and `get_redis_connection` just  return a raw redis connection (with the connection pool inside of them) so I'm pretty confused why it does not work properly.

Is `django-rq` maintains persistent connections? Is `django-rq` executes in different process?
The second question will be the cause why the connection number is not increasing in django process...

**Comment by selwin** [comment]
Yes, actually the worker does call `os.fork`, but it uses the same Redis connection. Does connection pooling not work across processes?

**Comment by niwinz** [comment]
The connection pool does not work across processes. When you call fork, the connection pool that your new process references now works in other memory space. In this case you can't see the connections created on your child process in the main process...
