### ISSUE TITLE
4.2.0 implicitly depends on msgpack

### ISSUE THREAD

**Issue by risicle** [niwinz/django-redis#164]
Due to doing an unconditional module-level `import msgpack` in `serializers/base.py` (https://github.com/niwinz/django-redis/blob/4.2.0/django_redis/serializers/base.py#L15) django-redis will fail if this is not installed. This dependency is not declared anywhere.

(Also, the tests fail without msgpack)

**Comment by niwinz** [comment]
You are completelly right! I will fix it! Thanks for notice!

**Comment by niwinz** [comment]
This should be fixed in 4.3.0 ;)
