### ISSUE TITLE
django.core.cache doesn't matching Redis object

### ISSUE THREAD

**Issue by anshulbisht06** [niwinz/django-redis#167]
This is cache configuration from settings.py -
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

And in django shell,
>>> from django.core.cache import cache
<django.core.cache.DefaultCacheProxy object at 0x7ff43723f050>
>>> r = get_redis_connection("default")
>>> r
Redis<ConnectionPool<Connection<host=127.0.0.1,port=6379,db=1>>>

Because this is not a StrictRedis/Redis object, I am unable to use get/set values using cache.set/cache.get .
>>> cache.set('a',123)    --> Not working
>>> cache.get('a')           --> Not working
 I always have to use the get_redis_connection("default") to set and get values from cache.
Can you suggest something that can solve my problem?
django-redis version --> 4.3.0

**Comment by niwinz** [comment]
Lamentably I'm not clearly understand your problem.

```python
>>> from django_redis import get_redis_connection
>>> get_redis_connection("default")
StrictRedis<ConnectionPool<Connection<host=127.0.0.1,port=6379,db=1>>>
```

**Comment by anshulbisht06** [comment]
Hello sir,
The problem arises when I use django cache methods. Getting/Setting values using cache.get/cache.set does not create any key-value pair in my redis database.
eg. >>> cache.set('a' 123)
But when I try to get this using redis-cli in my terminal, it returns (nil). That means no key is set.
127.0.0.1:6379> GET 'a'
(nil)
>>> cache.get('a',None)
None

**Comment by niwinz** [comment]
Ok, this is a expected behavior, the django cache interface by default prefix all keys with the version. This makes not possible retrieve as is the same keys using raw redis connection.

If you connect to redis using redis-cli ang executes `keys *` in the apropriate database you will see that keys that you are setting using django cache interface are all prefixed.
