### ISSUE TITLE
cache.clear() clears ignores KEY_PREFIX

### ISSUE THREAD

**Issue by ostcar** [niwinz/django-redis#168]
The current implementation of clear is:
```python
    def clear(self, client=None):
        """
        Flush all cache keys.
        """
        if client is None:
            client = self.get_client(write=True)

        client.flushdb()
```
The last line clears the hole redis database and not only the keys starting the configured KEY_PREFIX

This happens as example, if different django caches are created with different KEY_PREFIX values.

One possible solution would be to use:
```python
    def clear(self, client=None):
        """
        Flush all cache keys.
        """
        self.delete_pattern("*")
```

**Comment by niwinz** [comment]
Yes! PR is welcome with that change!

**Comment by utapyngo** [comment]
KEY_PREFIX is ignored again in 4.6.0 after "fixing" https://github.com/niwinz/django-redis/issues/223 in https://github.com/niwinz/django-redis/commit/a71d9fbc3a455fcd739e59b884c4c7e99bc21ff5: `client.scan_iter("*")` iterates over all keys.
