### ISSUE TITLE
Needs test client

### ISSUE THREAD

**Issue by arnuschky** [niwinz/django-redis#170]
Currently, there's no easy way to do integration tests that depend on django-redis. Best would be to allow for a memory-only redis instance, similar to what's done for the database.

Options are mockredispy (https://github.com/locationlabs/mockredis) or fakeredis (https://github.com/jamesls/fakeredis). Ideally, this would be specified in `settings.py`. 

Alternatively, a custom `StrictRedis` class could be specified (eg, mockredis.client.MockRedis)

**Comment by niwinz** [comment]
If you are using just the django interface for cache, you can just use django's builtin in memory cache backend. In the other hand implementing all the django-redis (redis) in memory seems like a overkill.

I found similar questions in the past and there are no good and pragmatic approach for that. In my apps I just use integration tests with real redis databases.

**Comment by arnuschky** [comment]
Hu. I thought that making the redis client used by django-redis configurable would solve the issue. That way, you don't need to implement anything; the user can simple specify an alternative client (provided by the above mentioned packages. Haven't ;ooked at your code yet; sorry if this is unfeasible in this context.

**Comment by niwinz** [comment]
Hmm, something like that you are mentioning it is completly feasible and it can be done by the user directly. At this moment it can be done overwritting the current connection factory settings, pointing it to your own that just overwrites the `get_connection` method (https://github.com/niwinz/django-redis/blob/master/django_redis/pool.py#L94).

Also we can improve the connection factory for hook the class getter, something like `get_connection_class` and in this case the user can do the same thing but much simpler.

If something like this will help you, it is completly feasible ;)
