### ISSUE TITLE
Include the version number in the module

### ISSUE THREAD

**Issue by BertrandBordage** [niwinz/django-redis#172]
It would be great if we could access the version number directly from the Python module `django_redis`, as it is the case in most Python packages, as it is suggested in [PEP 8](https://www.python.org/dev/peps/pep-0008/#version-bookkeeping) and [PEP 396](https://www.python.org/dev/peps/pep-0396/) (even though this last one was deferred).

It could be implemented [like in Django](https://github.com/django/django/blob/master/django/__init__.py), with a `VERSION` tuple and the `__version__` string would be generated from it. Of course, other mentions of this version number (like in setup.py) should import one of these two variables.

**Comment by niwinz** [comment]
A PR is welcome with the django's approach ;)

**Comment by BertrandBordage** [comment]
Done!
