### ISSUE TITLE
wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by sevenguin** [niwinz/django-redis#175]
When i use `request.session[0]='xxx', return HttpResponse(None), then raise a ResponseError:wrong number of arguments for 'set' command

it's raised from 'django_redis/client/default.py in set', why ?

**Comment by niwinz** [comment]
Very strange, can you tell me the versions that are you using.

**Comment by sevenguin** [comment]
django - 1.9
django-redis - 3.0.6

error info
Django Version:	1.9
Exception Type:	ResponseError
Exception Value:	
wrong number of arguments for 'set' command
Exception Location:	/Users/weill/anaconda/lib/python3.5/site-packages/redis/connection.py in read_response, line 574

I can not understand this step:
**django_redis/client/default.py in set**
```
        return client.set(nkey, nvalue, nx=nx, ex=timeout, xx=xx)  #raise from here, kwargs is {}, args is valued
except _main_exceptions as e:
        raise ConnectionInterrupted(connection=client, parent=e) 
```

**Comment by niwinz** [comment]
django-redis 3.0.6?  That version has never exists.

**Comment by niwinz** [comment]
Can you provide also redis-py version and proper django-redis version?

**Comment by sevenguin** [comment]
Sorry, the version of redis is 3.0.6,  redis-py version is 2.10.3  django-redis installed by 'pip install django-redis', should be the lasted

**Comment by sevenguin** [comment]
django-redis version is 4.3.0

**Comment by niwinz** [comment]
I have added session tests from django and all passes under that configuration. It seems that something wrong is in your environment.
The exception and the location of this exception indicates that something wrong is happens in redis side, like it does not accept the SET operation.

Lamentably I can't help much more in this. Let me know anything ;)

**Comment by sevenguin** [comment]
Thanks anyway, I will try it in other environment.

**Comment by mjl** [comment]
I encountered the same problem, it indeed looks like a redis error message.

```
$ python manage.py shell

>>> from django.core.cache import cache
>>> cache.set("bar", "baz")

>>> Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "...lib/python2.7/site-packages/django_redis/cache.py", line 25, in _decorator
    return method(self, *args, **kwargs)
  File "...lib/python2.7/site-packages/django_redis/cache.py", line 59, in set
    return self.client.set(*args, **kwargs)
  File "...lib/python2.7/site-packages/django_redis/client/default.py", line 159, in set
    return client.set(nkey, nvalue, nx=nx, ex=timeout, xx=xx)
  File "...lib/python2.7/site-packages/redis/client.py", line 1072, in set
    return self.execute_command('SET', *pieces)
  File "...lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "...lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "...lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: wrong number of arguments for 'set' command
```

 I gradually downgraded my django-redis until the problem went away. It seems that first occurred with django-redis 4.0, with django-redis 3.8.4 the above works fine:

```
>>> from django.core.cache import cache
>>> cache.set("bar", "baz")
True
```

Since nobody else seems to have that problem, perhaps it's an incompatibility with the redis version. I run redis 2.4.15 here.

I then captured the attempted command via netcat, it looks as if the old (working) django-redis uses a SETX command, and the new (non-working) django-redis uses a SET command with an additional EX parameter tacked onto the end.

The redis docs say this:

> Starting with Redis 2.6.12 SET supports a set of options that modify its behavior:
> EX seconds -- Set the specified expire time, in seconds.

Quite obviously, my redis version is too old here.

**Comment by niwinz** [comment]
Thanks. 

If you are using old version of redis server, you should use 3.x branch. The docs says clearly the redis server version support for each branch: http://niwinz.github.io/django-redis/latest/#_requirements

```
1.4.2. Redis Server Support
- django-redis 3.x.y will maintain support for redis-server 2.6.x and upper.
- django-redis 4.x.y will maintain support for redis-server 2.8.x and upper.
```

**Comment by chuangying2017** [comment]
I use django-redis4.8 version django2.0 Then there are some mistakes such as: wrong number of arguments for 'set' command

**Comment by ap75** [comment]
Hi!
I have created new django project and have installed:
`pip list
Package      Version
------------ -------
Django       2.2.7
django-redis 4.10.0
pip          19.3.1
pytz         2019.3
redis        3.3.11
setuptools   40.8.0
sqlparse     0.3.0`
OS: Windows 10; Redis server 2.4.5 (It works good with other project)

Then I've added section to settings.py:
`CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache" # or .cached_db
SESSION_CACHE_ALIAS = "default"`

After migrating and creating superuser I try to start local server and connect to http://127.0.0.1:8000/admin/
When I was redirected to login/?next=/admin/, I've seen the error page:
`Request Method: | POST
http://127.0.0.1:8000/admin/login/?next=/admin/
ResponseError
wrong number of arguments for 'set' command`
[...]
`Variable | Value
-- | --
client | Redis<ConnectionPool<Connection<host=127.0.0.1,port=6379,db=0>>>
index | 0
key | 'django.contrib.sessions.cacheic72mihd6xwhwt4cwromtzceoih3yc1x'
nkey | ':1:django.contrib.sessions.cacheic72mihd6xwhwt4cwromtzceoih3yc1x'
nvalue | b'\x80\x04}\x94.'
nx | True
original_client | None
self | <django_redis.client.default.DefaultClient object at 0x000001A2DB9B00F0>
timeout | 1209600000
tried | []
value | {}
version | None
xx | False

`

What is wrong?

**Comment by mjl** [comment]
> wrong number of arguments for 'set' command`
>
> What is wrong?

Your redis server version 2.4 is too old. See this post just above yours:

https://github.com/niwinz/django-redis/issues/175#issuecomment-188755176

**Comment by ap75** [comment]
> wrong number of arguments for 'set' command` What is wrong?
> Your redis server version 2.4 is too old. See this post just above yours: [#175 (comment)](https://github.com/niwinz/django-redis/issues/175#issuecomment-188755176)

Thank You!
I will try newer Redis on Windows

**Comment by ap75** [comment]
It works fine! Thank You very much! )

**Comment by kittinan** [comment]
I got the error message on Redis server v=2.8.4

```
django==3.0.5
celery==4.4.2
django-celery-results==1.2.1
django-redis==4.11.0
```

Error message:
```
redis.exceptions.ResponseError: wrong number of arguments for 'ping' command
```

After I upgrade the Redis server to 5.0.8 that **work fined!**
