### ISSUE TITLE
cache_page function key_prefix doesn't play nicely with cache.keys or cache.delete_pattern

### ISSUE THREAD

**Issue by squarebraces** [niwinz/django-redis#178]
I understand that version number is inserted before the key as a prefix by django-redis. The problem is that this is prefixed 'before' django prefixes it with the key_prefix specified in the cache_page function.

For eg:
1. Doing @cache_page(timeout) will generate a key of the form - ":1:views.decorators.cache...."
-  django-redis keys() and delete_pattern() will respond to the expression "views*",  silently abstracting the version prefix.

2. Doing @cache_page(timeout, key_prefix="myprefix") generates a key of the form "myprefix:1:views.decorators.cache..."
-  django-redis keys() and delete_pattern() are not able to find these keys at all.

We want to use the key_prefix attribute of the cache_page function to selectively scan and delete keys using the command delete_pattern("myprefix*")

Is there a workaround short of interacting with the raw connection? We are still using Django 1.6.5 and don't know if this is actually a bug in Django.

PS: apologies for opening an empty issue earlier - typo ended up sending enter.

**Comment by niwinz** [comment]
This is something that is not supported.

The workaround will be do the same thing that django does on prefixing key and execute the underlying code of delete_pattern of django redis.

I'll keem this open to think how it can be solved. If you found a solution before, please send a PR ;)

**Comment by niwinz** [comment]
Should be fixed with the latest release.
