### ISSUE TITLE
Redis cluster implementation?

### ISSUE THREAD

**Issue by thoas** [niwinz/django-redis#182]
I'm looking to link [redis-py-cluster](https://github.com/Grokzen/redis-py-cluster), is this something already done somewhere?

Thank you :)

**Comment by niwinz** [comment]
Not, this is just a django cache client. It has the facility of plugable clients so a cluster client can be easy implemented with django-redis facilities, but as this moment I am not aware of some one have done it.

**Comment by CombatCode** [comment]
django-redis seems to be working with Azure Redis Cache Cluster via default Client, as now only delete_many  doesn't working, but delete does
