### ISSUE TITLE
New version number

### ISSUE THREAD

**Issue by Tyndie** [niwinz/django-redis#183]
Can you release a new version number please? 4.3.0 Is about 5-6 months old.

**Comment by niwinz** [comment]
Of course, I have plans release new version soon.

**Comment by LeaFin** [comment]
Will the new version support Django 1.9? Or does 4.3.0 already support 1.9?

**Comment by niwinz** [comment]
There is nothing in django-redis that can you avoid to use it with django 1.9.

In any case, today or tomorrow I'll try take time and add django 1.9 to the test suite and release new version.

**Comment by niwinz** [comment]
new version released
