### ISSUE TITLE
UnicodeDecodeError after switching to Python 3

### ISSUE THREAD

**Issue by kz26** [niwinz/django-redis#184]
I'm in the process of refactoring a Django project that uses django-redis for Python 3 compatibility. Running into the following issue with django-redis:

`'ascii' codec can't decode byte 0xe0 in position 1: ordinal not in range(128)`
`/lib/python3.4/site-packages/django_redis/serializers/pickle.py in loads, line 43`

The data being cached is a Python dictionary with unicode keys and values. This worked without issue on Python 2.7, but no longer seems to work on Python 3.

Django version is 1.8.10 and django-redis is 4.3.0.

**Comment by kz26** [comment]
Never mind, this was fixed by flushing Redis to remove old cached items!

**Comment by thinkt4nk** [comment]
I'm having this issue even after running `python manage.py invalidate_cachalot`. Shouldn't that blow out any offending py2 keys?

**Comment by lalzada** [comment]
any other solution if i don't want to flush redis data but wants to upgrade django-redis?
