### ISSUE TITLE
Using sentinel

### ISSUE THREAD

**Issue by kaldown** [niwinz/django-redis#186]
What is the right way of using django_redis_sentinel?
So when I shutdown my master, cache would be written by cache.set() unless slave becomes a master.
And one more thing, I've found a degradation of caching big amount of data (whole countries around the world) needs to be returned in 15 seconds, with redis in kinda half second, with sentinel in 1-1.5 seconds.
Is there any way to improve logic of using redis-sentinel, or any alternatives. 
How do you solve failover?
Thanks.

**Comment by niwinz** [comment]
Unfortunatelly I'm not using sentinel, so I can't help you there. django-redis does not support sentinel.
