### ISSUE TITLE
weird issues with latest

### ISSUE THREAD

**Issue by azrethos** [niwinz/django-redis#187]
'LocMemCache' object has no attribute 'client'

**Comment by azrethos** [comment]
it would appear my settings.py has not loaded yet, but it is looking up the cache value django 1.8

**Comment by azrethos** [comment]
4.3.0 and before work 100% fine

**Comment by niwinz** [comment]
It is very strange because, the cange made in the `__init__.py`  does not change any behavior, the same behavior will happen independently of the introduced change: in both versions if you have locmem configured it will raise that exception...

**Comment by niwinz** [comment]
Additional check is added to that function for avoid wrong exception and `4.4.1` is released. 

But, I'm pretty sure that instead of `AttributeError` now you will found the `notimplementederror`...

**Comment by azrethos** [comment]
I do not use LocMemCache, as far as I know. It must be a default setting; all of this happens BEFORE my settings.py loads

in my manage.py, here is what I was doing

  ```
      from django.conf import settings as django_settings
      django_settings.configure()
      try:
            redis = get_redis_connection()  # <------ this raises the LocMemCache
            redis.ping()
        except ConnectionError:
            raise Exception('You need to start redis')

```

**Comment by azrethos** [comment]
I Updated to 4.3.1, here is the error

```

Traceback (most recent call last):
  File "./manage.py", line 69, in <module>
    main()
  File "./manage.py", line 40, in main
    redis = get_redis_connection()
  File "/home/user/.virtualenvs/lagapps3/local/lib/python2.7/site-packages/django_redis/__init__.py", line 24, in get_redis_connection
    raise NotImplementedError("This backend does not supports this feature")
NotImplementedError: This backend does not supports this feature
```

**Comment by azrethos** [comment]
Note: 4.3.0 works 100% fine in the same enviroment

**Comment by niwinz** [comment]
Hmm, independently if that was worked properly with previous version, I see that you are using wrongly the django initialization. If you want something run in django context you should execute the `django.setup()` function that initializes all django stuff: https://docs.djangoproject.com/en/1.9/ref/applications/#initialization-process

The 4.4.1 throws proper exception, with previous versions this exception was ignored or something similar, I don't know why that not happen before.

**Comment by azrethos** [comment]
django removing the

```
from django.conf import settings as django_settings
      django_settings.configure()
```

fixes it, thanks
