### ISSUE TITLE
return value of cache.ttl() is None

### ISSUE THREAD

**Issue by ayasiee** [niwinz/django-redis#193]
Hi.

I'm use django-redis to use cache. and my python version is 3.4.3.

I have a problem with return value of cache.ttl() is None although key/val is not persistent.

the point is
`(t >= 0 and t or None)`
https://github.com/niwinz/django-redis/blob/master/django_redis/client/default.py#L424

when t is 0, this statement returns None.

would you please modify this code to like:

```
if t >=0
 return t
else:
 return None
```

thanks

**Comment by niwinz** [comment]
PR is welcome if you want quick fix of that issue.

**Comment by ayasiee** [comment]
thanks for your reply.

i can pull request but i didn't. because there is 2 choices. and i can not decide which is correct.

let me see.
in document (http://niwinz.github.io/django-redis/latest/#_get_ttl_time_to_live_from_key)

```
It returns:

* ttl value for any volatile key (any key that has expiration)
* 0 for expired and not existent keys
* None for keys that does not have expiration
```
0 is confusing.
1. if key does not exists or expired, returns 0
2. value for any volatile key which ttl is less than 1 seconds

if you choose backward compatibility,
```
  if t>=0:
    return t
  else:
    return None
```
is enough. but confusing 0 is left.

if you choose solve confusing 0,
```
  t=client.pttl(key)
  if t > 1000:
    return int(t/1000)  
  elif t > 0:
    return t/1000
  else:
    return None
```
is one of the solution. (if ttl < 1, ttl is float)

how about your opinion?
