### ISSUE TITLE
How to setup lock timeout correctly?

### ISSUE THREAD

**Issue by onegreyonewhite** [niwinz/django-redis#194]
I`m using 
```
with CACHE.lock(key):
    some_thing()
```
How to setup lock timeout? I can`t find any info in docs.

**Comment by niwinz** [comment]
It accepts the same parameters as the underlying `redis-py` library `.lock` method. You are right, it is not extensively documented, as a workaround you can see just the method declaration: https://github.com/niwinz/django-redis/blob/master/django_redis/client/default.py#L231
