### ISSUE TITLE
Encrypt data

### ISSUE THREAD

**Issue by onegreyonewhite** [niwinz/django-redis#195]
It lacks encryption packets transmitted packets between Django and redis. It would be very cool if it would be possible to encrypt the packets to someone overheard critical data on the channel.
How to look at [here](https://github.com/vingd/encrypted-pickle-python) is the library?

PS: Sorry for my bad english...

**Comment by niwinz** [comment]
Almost everything about security and redis is already explained here: http://redis.io/topics/security

Additionally:
- encrypting data will make imposible use redis atomic operations over integers or similar things.
- proper encryption scheme will take too much space in comparison to plain values (imagine a integer counter, that will use 4 bytes unencrypted but at least will use 16 bytes + (N bytes of auth tag) for storing it.

If you need just transport encryption, my recommendation is use something a secure tunel/proxy that solves very well that problems using strong and well testeted encryption schemes. If you really want is encrypt the content, you can implement a plugabble client on top of default one (django-redis, has the notion of pluggable clients) that just acts as middleware and encrypts the data with the encryption scheme that you need.

**Comment by onegreyonewhite** [comment]
Could you merge https://github.com/niwinz/django-redis/pull/196? There is no conflicts, but may be helpful for other.

**Comment by niwinz** [comment]
Close, because of reasons already explained in #196
