### ISSUE TITLE
ResponseError, When use cache.keys

### ISSUE THREAD

**Issue by hjc1702** [niwinz/django-redis#197]
![bug](https://cloud.githubusercontent.com/assets/5949988/15506218/63319d84-21f9-11e6-8622-cfd908b69057.png)
my python version is 2.7.5, Django version is 1.9.2, django-redis version is 4.4.3

**Comment by niwinz** [comment]
This seems like a redis is rejecting the command. This is not an django-redis issue, seems like you are using incompatible redis database or redis-py library version.

**Comment by hjc1702** [comment]
thanks
