### ISSUE TITLE
redis:// format is not able to handle passwords with '#'

### ISSUE THREAD

**Issue by nikunjbadjatya** [niwinz/django-redis#201]
Hello,

Using django_redis 4.4.3 with django 1.6.3 and python 2.7.6 on ubuntu 14.04.
My LOCATION comes to be like this: 
`'redis://qwerty#asdfg@<my ip>:6379/3'`

I am getting this error:

`Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "./apps/auth/middleware.py", line 27, in process_request
    user = auth.authenticate(userinfo=request.COOKIES.get('user_id', None))
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "./apps/auth/backends.py", line 114, in authenticate
    userinfo = cache.get('user_%s' % userinfo)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
ConnectionError: Error -2 connecting to vewsaxz78ui:6379. Name or service not known
`

**Comment by niwinz** [comment]
This is not django-redis issue, the uri connection handling is done on the underlying redis-py library. 

Although, I see that the password part of  your LOCATION misses `:` on start.

**Comment by nikunjbadjatya** [comment]
`redis://[:qwerty#asdfg]@<my ip>:6379/3` Is this the right format for password `[:password]  Or :password  Or password`only ?
documentation does not clearly explains this.
Thanks.

**Comment by spendyala** [comment]
Use the URL encoded of password and enable the connection pool url decode to be true. 

Add the following in `OPTIONS`
`'CONNECTION_POOL_KWARGS': {'decode_components': True}` 
and 
use the password `qwerty#asdfg` to be `qwerty%23asdfg` 

Correct format of URL will be `redis://[:qwerty%23asdfg]@<my ip>:6379/3`

**Comment by nikunjbadjatya** [comment]
Great Veera!

It works that way.

You are awesome.

@authors: Probably this should be added in your README or something.

Cheers,
Nikunj

**Comment by niwinz** [comment]
thanks, I'll add it to the documentation.
