### ISSUE TITLE
Password with hash

### ISSUE THREAD

**Issue by spendyala** [niwinz/django-redis#205]
Redis password that contians `#` are failling now for example

`abc#123` is not parsed correctly. 
`ParseResult(scheme='redis',
netloc=':abc', path='', params='', query='', fragment='123@localhost:6379/0')`

**Comment by spendyala** [comment]
Earlier we are able to pass the `PASSWORD` in `OPTIONS` now that feature is not there.

**Comment by niwinz** [comment]
Duplicated (see #201 and #203).
