### ISSUE TITLE
Setting multiple redis instances.

### ISSUE THREAD

**Issue by NirmalVatsyayan** [niwinz/django-redis#207]
Can any please tell me how to configure multiple redis instance with SSL socket option, password and DB option in django settings.

**Comment by niwinz** [comment]
Can you elaborate more a little bit your problem. This seems like that is already explained in the documentation.

**Comment by NirmalVatsyayan** [comment]
yes, i just went through doc again. Found it, i was actually asking for way to use redis on cluster, way to use master slave configuration is provided. Thanks.
