### ISSUE TITLE
Redis Cluster support.

### ISSUE THREAD

**Issue by roboslone** [niwinz/django-redis#208]
Redis supports clustered installations since version 3.0 - http://redis.io/topics/cluster-spec.

Adding multiple cluster nodes to `LOCATION` setting seems to work (I think RedisCache only connects to first parsed address, but I'm not sure), but it really doesn't.

For example I have 6 instances (3 masters, 3 slaves), so I add them to my `CACHES/default/LOCATION`: `redis://example.com:7000,redis://example.com:7001,...`
Then I try to read key, that is actually on example.com:7004 and get `ResponseError: MOVED 9445 127.0.0.1:7004`.

Using `ShardClient` or `HerdClient` with list of locations doesn't work either.

Please suport Redis Cluster!

**Comment by niwinz** [comment]
Redis Cluster is not supported by django-redis. If you put multiple conn strings in location they will act as master slave configuration.

On the other hand I don't have plans to have redis cluster support builtin, the main reason is because I'm not going to use it and I'm the only one maintainer of django-redis. Maintaining code that you don't know how it works on my free time does not make sense for me. 

Howerver django-redis design with its pluggable clients allows do it out of the `django-redis` codebase. You can implement it out of the `django-redis` codebase and publish it as a plugin for django-redis for who wants to use redis cluster setup. Feel free to develop that and when is ready, let me know about it and I'm gladly reference it on the documentation.

**Comment by kottenator** [comment]
Just in case if it's still interesting to you, dear visitor: here's a solution I've found: use [redis-py-cluster](https://github.com/Grokzen/redis-py-cluster):

```py
CACHES = {
  'default': {
    'BACKEND': 'django_redis.cache.RedisCache',
    'LOCATION': 'redis://XXX.YYY.ZZZ.cache.amazonaws.com/0',
    'OPTIONS': {
      'REDIS_CLIENT_CLASS': 'rediscluster.RedisCluster',
      'CONNECTION_POOL_CLASS': 'rediscluster.connection.ClusterConnectionPool',
      'CONNECTION_POOL_KWARGS': {
        'skip_full_coverage_check': True # AWS ElasticCache has disabled CONFIG commands
      }
    }
  }
}
```

**Comment by sonic182** [comment]
> Just in case if it's still interesting to you, dear visitor: here's a solution I've found - use [redis-py-cluster](https://github.com/Grokzen/redis-py-cluster):
> 
> ```python
> CACHES = {
>   'default': {
>     'BACKEND': 'django_redis.cache.RedisCache',
>     'LOCATION': 'redis://XXX.YYY.ZZZ.cache.amazonaws.com/0',
>     'OPTIONS': {
>       'REDIS_CLIENT_CLASS': 'rediscluster.RedisCluster',
>       'CONNECTION_POOL_CLASS': 'rediscluster.connection.ClusterConnectionPool',
>       'CONNECTION_POOL_KWARGS': {
>         'skip_full_coverage_check': True # AWS ElasticCache has disabled CONFIG commands
>       }
>     }
>   }
> }
> ```

This didn't work to me, but this worked to me


```python
# custom CLIENT_CLASS
from rediscluster import RedisCluster
from django_redis.client import DefaultClient


class CustomRedisCluster(DefaultClient):

    def connect(self, index):
        """Override the connection retrival function."""
        return RedisCluster.from_url(self._server[index])
```

```python
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis1',
        'OPTIONS': {
            'CLIENT_CLASS': 'myapp.redis.CustomRedisCluster',
        }
    }
}
```

**Comment by cKurultayKalkan** [comment]
Hello @sonic182,

Thank you for your solution. It helped me to find a new one. 

I had same problem when i wanted to use redis-py version 4.0 with django redis. 

Because of **redis-py-cluster doesn't support redis-py 4.0**, i had to use RedisCluster  from redis-py lib directly. 

Finally,



_**redis_custom_client.py**_

```python3
from redis import RedisCluster
from django_redis.client import DefaultClient


class CustomRedisCluster(DefaultClient):

    def connect(self, index):
        """Override the connection retrival function."""
        return RedisCluster.from_url(self._server[index])
```


**_settings.py_**
```python3
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "redis_client.CustomRedisCluster",
        },
    }
} 
```

**Comment by delav** [comment]
i want to costom redis client, but when i use

`from django.core.cache import cache`
`cache.hset(key, field, value)`

i get this error as follow:
```
  File "C:\Users\test\venv\lib\site-packages\django\utils\connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
AttributeError: 'RedisCache' object has no attribute 'hset'
```
my version
Python:  3.7
Django: 3.2
django-redis: 5.3


django settings.py
```
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL',
        'OPTIONS': {
            'CLIENT_CLASS': 'infra.django.cache.redisclient.RedisClient'
        },
    }
}
```
redisclient.py
```
from django_redis.client.default import DefaultClient


class RedisClient(DefaultClient):

    def hset(self, key, field, value, version=None, client=None):
        key = self.make_key(key, version=version)
        client = client or self.get_client(write=True)
        return client.hset(key, field, value)

    def hget(self, key, field, version=None, client=None):
        key = self.make_key(key, version=version)
        client = client or self.get_client(write=True)
        return client.hget(key, field)

    def hgetall(self, key, version=None, client=None):
        key = self.make_key(key, version=version)
        client = client or self.get_client(write=True)
        return client.hgetall(key)

    def hdel(self, key, field, version=None, client=None):
        key = self.make_key(key, version=version)
        client = client or self.get_client(write=True)
        return client.hdel(key, field)

    def hlen(self, key, version=None, client=None):
        key = self.make_key(key, version=version)
        client = client or self.get_client(write=True)
        return client.hlen(key)

    def hkeys(self, key, version=None, client=None):
        key = self.make_key(key, version=version)
        client = client or self.get_client(write=True)
        return client.hkeys(key)

    def hexists(self, key, field, version=None, client=None):
        key = self.make_key(key, version=version)
        client = client or self.get_client(write=True)
        return client.hexists(key, field)
```

How can I configure it correctly ?

**Comment by backend-seokyung-kim** [comment]
Has anyone experienced high connection counts when using @cKurultayKalkan's solution?

I am running a server with several Redis servers organized in both Sentinel and Cluster modes on AWS ElastiCache.

However, when using Cluster mode, the number of current connections is nearly 2–3 times higher than in Sentinel mode (using DefaultClient).

If anyone has any insights or potential solutions regarding this issue, please let me know. Thanks!
