### ISSUE TITLE
Use raw key to fetch data from redis.

### ISSUE THREAD

**Issue by NirmalVatsyayan** [niwinz/django-redis#209]
Hi, I was actually hoping is there any way to use raw key to fetch data from redis in django-redis. Django changes the key passed internally but Django also provides a way to override make_key function and pass 'KEY_FUNCTION' : make_key, in setting of caches to use raw key.

I did same in django-redis to fetch raw data which was populated in redis from some other process, so could not actually use django's customized way to change passed key and then fetch data.

my make key function is very plain 

    def make_key(key, key_prefix, version):
        return key

   And i also entered :  'KEY_FUNCTION' : make_key , in redis configuration of caches.

by default in django it returns 
return ':'.join([key_prefix, str(version), key])

To be precise, i was hoping if i pass, "key" then redis data having "key" as key should be fetched, it should not be altered in mid way. Similarly if i write using key as "key", it should not be altered in mid way. Kindly let me know please.

This is really important to me for my project, please let me know is there is any way to do this.

**Comment by niwinz** [comment]
django cache subsystem has the concept of the version and this is encoded in the key, this is because the key stored in redis is not exact to one that user pases.

If you want to access in raw, maybe you want baypass the django layer and just access to redis. django-redis exposes a facilities for do it taking advantage of the connection pooling and django facilities on configuration. For more info: http://niwinz.github.io/django-redis/latest/#_raw_client_access

**Comment by NirmalVatsyayan** [comment]
Yes, i tested this way of connecting and thanks it is working awesome.
Will it also work on multiple instances of redis configured in setting for cluster or master/slave.
Also, had a silly question, does this creates and closes connection every time i request to redis?

Thanks for your quick response again.

**Comment by niwinz** [comment]
For write operations it will always choice the master redis server but if you pass `write=False` to the `get_redis_connection`, it will choice a random slave redis server (https://github.com/niwinz/django-redis/blob/master/django_redis/__init__.py#L7)

About connection management, it uses connection pool internally so no, the connection lives sometime before it closed.

**Comment by NirmalVatsyayan** [comment]
Thanks a lot.
It was really helpful.
