### ISSUE TITLE
[Proposal]  Migrate password from uri to option 'PASSWORD'

### ISSUE THREAD

**Issue by mort1k** [niwinz/django-redis#214]
I propose to move password from the url to the option parameter, because when debug = True, the passwords are visible to all.

**Comment by niwinz** [comment]
Hmm, agree with the exception that the default behavior should be maintained. The `PASSWORD` key should be additional to the one on the URI, but it should have priority over the password set set in the URI.

PR is welcome ;)

**Comment by lingcen000** [comment]
`CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://[:sen]@192.168.137.101:6379',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}`

this is my config in the settings.py, it response invalid password on the page
but I can use the redis by the password  through the command line

**Comment by niwinz** [comment]
@lingcen000 this is because you should remove the `[` and `]` characters from the final connection uri. That characters are used in documentation for denote that that part is optional.

For the rest, I on my wedding so I can't have time for this for this moment. My apologies.

**Comment by niwinz** [comment]
Already implemented in master and will be available in next version ;)
