### ISSUE TITLE
Support get_or_set

### ISSUE THREAD

**Issue by jeffnuss** [niwinz/django-redis#219]
Django's built in caching API provides a [`get_or_set` method](https://docs.djangoproject.com/en/1.10/topics/cache/#basic-usage) (as of 1.9). It would be nice if django-redis supported this as well.

**Comment by niwinz** [comment]
As far as I can understand, `django-redis` already supports it, just because the base backend of django which django-redis extends comes with default implementation.

**Comment by jeffnuss** [comment]
I certainly haven't taken a deep dive, I just didn't see it implemented in the code and when I've tried using it, I get the error `{AttributeError}'RedisCache' object has no attribute 'get_or_set'`

**Comment by jeffnuss** [comment]
And I'm an idiot... I'm looking at a django 1.8 project... My bad. Nothing to see here.
