### ISSUE TITLE
External Source Data

### ISSUE THREAD

**Issue by nhzc123** [niwinz/django-redis#222]
When I use `cache.set("param", "test")` 
It seems that the key "param" would add prefix string ":1:"
so when I check from redis-cli it will appears as ":1:param" 

Now I need to set lots of data from external sources 
For example I want to set ("hello", "world") from redis-cli tool

But I get  empty result from `cache.set("hello")` 

So I try to set (":1:hello", "world") from redis-cli tool but an error called "unpickling stack underflow" occur

How can I set data from external source and get data from django-redis command?

Thx

**Comment by niwinz** [comment]
About prefixes, it is explained many times in different issues: https://github.com/niwinz/django-redis/issues/167 https://github.com/niwinz/django-redis/issues/209 (this links are just for additional info)

django-redis by default serializes the data using pickle protocol. So if you set the data externally, you should properly serialize the data in the same way as django-redis expects (in this case just use python pickle module). 

In case of you need a more inter-operable serialization format, you can change the default to any other that comes with django-redis or just create a own one.
