### ISSUE TITLE
Since 4.4.0, .clear() does not completely clear its cache

### ISSUE THREAD

**Issue by lddubeau** [niwinz/django-redis#223]
### Versions

Django: 1.10 (but I don't think the specific Django version is a factor)
django-redis: 4.4.0 and higher.

### Steps to reproduce

Run this:

```
import os

from django.conf import settings
settings.configure()

from django.core.cache.backends.filebased import FileBasedCache
from django_redis.cache import RedisCache

def dump(label, cache, key, version):
    print label, "key:", key, "version:", version, "result:", \
        cache.get(key, version=version)

def test_cache(label, cache):
    cache.set("foo", 1)
    cache.set("foo", 2, version=2)
    dump(label + " before clear", cache, "foo", 1)
    dump(label + " before clear", cache, "foo", 2)
    cache.clear()
    dump(label + " after clear", cache, "foo", 1)
    dump(label + " after clear", cache, "foo", 2)

# You must be able to create files at this location.
fb_cache = FileBasedCache("/tmp/fb", {})
test_cache("fb_cache", fb_cache)

# Change this if localhost:6379 is not okay.
redis_cache = RedisCache("localhost:6379", {})
test_cache("redis_cache", redis_cache)
```

### Expected Results

After the call to `cache.clear()`, getting old keys should no longer return any results. So:

```
fb_cache before clear key: foo version: 1 result: 1
fb_cache before clear key: foo version: 2 result: 2
fb_cache after clear key: foo version: 1 result: None
fb_cache after clear key: foo version: 2 result: None
redis_cache before clear key: foo version: 1 result: 1
redis_cache before clear key: foo version: 2 result: 2
redis_cache after clear key: foo version: 1 result: None
redis_cache after clear key: foo version: 2 result: None
```

We see that both the file based cache and the redis cache return behave the same before and after `.clear()` is called.

These expected results can be obtained with any version of django-redis prior to 4.4.0.

### Actual Results

With 4.4.0 or higher:

```
fb_cache before clear key: foo version: 1 result: 1
fb_cache before clear key: foo version: 2 result: 2
fb_cache after clear key: foo version: 1 result: None
fb_cache after clear key: foo version: 2 result: None
redis_cache before clear key: foo version: 1 result: 1
redis_cache before clear key: foo version: 2 result: 2
redis_cache after clear key: foo version: 1 result: None
redis_cache after clear key: foo version: 2 result: 2
```

The last line of the output is where there is a problem. The key `foo` with version 2 was not cleared from the cache.

### Observations

This is not a theoretical problem, but one that actually happens in production. People using Django CMS and configuring it to have Django CMS' page cache use a cache that uses django-redis will run into problems because Django CMS makes substantial use of versioning. The net effect on Django CMS is that after the cache has been "cleared", some keys remain in the cache and eventually as the CMS increases the current version of the keys in the cache it will hit old keys and send stale data to clients. I was lucky that I've run into the problem while performing testing on one of my sites. Tests that used to pass stopped passing. When I inspected the HTML returned by Django, it looked test B was receiving data that would have been generated by test A. I did clear my caches correctly so I was at a loss as to where the problem was coming from. The tests started passing again after I reverted django-redis to 4.3.0.

I'm convinced the that problem lies wholly in django-redis. Django's [documentation for caches](https://docs.djangoproject.com/en/1.10/topics/cache/#basic-usage) says:

> Be careful with this; clear() will remove everything from the cache, not just the keys set by your application.

It is not clear what the scope of the `.clear()` is but for as long as I can remember, I've know this to mean that Django won't care about the key prefix set with the cache. And indeed if you examine the code of any of cache backends bundled with Django, you'll find that none of them care about the key prefix when they clear the cache. The DB-based one, for instance, does a plain "DELETE FROM [[table]]". This nukes everything in the table. The file based cache will exclude a suffix that is added to all the files created for the cache but does not otherwise care about what key prefix is used by the cache. 

And yes, this means that if Django's settings declare two caches with different prefixes but pointing to the same location, then when I clear one cache I'm also clearing the other. This is how Django caches behave.

Looks to me like pull request #169 is where things went astray.

**Comment by niwinz** [comment]
The fix is committed to master, can you please check if that fixes this issue (as double check) before release the 4.6.0 ?

**Comment by lddubeau** [comment]
I confirm that the problem does not happen anymore when I install from the master branch of the repo.

**Comment by niwinz** [comment]
Nice, I'll release a new version of django-redis ASAP (today), thanks for report and test.

**Comment by niwinz** [comment]
Released!
