### ISSUE TITLE
Question regarding incr() implementation

### ISSUE THREAD

**Issue by afrosimon** [niwinz/django-redis#224]
At first I assumed the incr() method would behave as the corresponding redis command (INCR or INCRBY) but it turns out an error is raised if the key does not exists. I've reviewed the code and similar issues and this seems to be deliberate; some problems in the past regarding the atomicity of the operation.

So what I'm wondering is, if the redis command is atomic in itself, why the lua script? Why not use the method contained in the "core" redis library : https://github.com/andymccurdy/redis-py/blob/d49aaacb7dd454781fd9cb2cd2cb92e9c07d7d31/redis/client.py#L999

In my current use case I can simply get the connection to the redis client underneath and use the function I've just linked. But I had to ask the question as I'm assuming there is some reason I do not understand somewhere in there.

**Comment by julen** [comment]
A side effect of this also is that using `incr()` in conjunction with `fakeredis` is not possible (very desirable for tests), since the latter doesn't implement the `eval` command.

**Comment by niwinz** [comment]
This is explained in https://github.com/niwinz/django-redis/issues/181 issue, and why it fixed using lua.

**Comment by afrosimon** [comment]
Still, why the need for the lua script if the underlying redis client can do the same thing : https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L999

Am I wrong in assuming this library is wrapping around redis-py to make it easy to interface with django?

**Comment by niwinz** [comment]
If you read carefully the referenced issue, You will notice that redis native command not solves the problem.

django-redis is a "cache backend for django" so for the first instance it provides a fully compliant cache backend (this means that it works under rules of the django cache backend interface). Later, it exposes many methods that allows to take advantage of redis functionallity, but without compromise the django cache backend interface. Later, if you need access to full redis functionality but to take advantage of the django redis connection management, you can use http://niwinz.github.io/django-redis/latest/#_raw_client_access
