### ISSUE TITLE
LOCATION connection via tcp fails 

### ISSUE THREAD

**Issue by Blquinn** [niwinz/django-redis#228]
I'm currently connecting to an amazon elasticache redis cluster from an ec2 server. Connection via redis-cli works flawlessly from my ec2. IE `redis-cli -h [my-aws-url]:6379` works, therefore it is not an aws configuration problem. 

My CACHES config looks like this:
`{'default': {'OPTIONS': {'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool', 'CLIENT_CLASS': 'django_redis.client.DefaultClient', 'PARSER_CLASS': 'redis.connection.HiredisParser', 'CONNECTION_POOL_CLASS_KWARGS': {'timeout': 20, 'max_connections': 50}}, 'LOCATION': 'redis://[my-aws-url]:6379', 'BACKEND': 'django_redis.cache.RedisCache'}}`

... which works on my local machine. 

However, on amazon I get this error: 
`ConnectionError: Error 111 connecting to localhost:6379. Connection refused.`

Which says to me that django-redis is not parsing the redis url correctly and instead attempting to force a localhost connection. 

Any ideas for configuration? 

PS there is no username and password for elasticache that I know of. The urls do appear to work if you have that info.

**Comment by niwinz** [comment]
Maybe the missing part is the db, the "LOCATION" setting should look like `redis://[my-aws-url]:6379/1`

**Comment by niwinz** [comment]
In any case, seems unrelated to django-redis. The url parsing is delegated to `redis-py` redis client.
