### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [niwinz/django-redis#231]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [django-redis](https://pypi.python.org/pypi/django-redis), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install django-redis with just the wheel, without having to do any extra work.

**Comment by niwinz** [comment]
Right now no one need to do any extra work, just `pip install django-redis`, why I should care about wheels?

**Comment by kevin-brown** [comment]
Pulling from http://pythonwheels.com/ ...

> Advantages of wheels
> 1. Faster installation for pure python and native C extension packages.
> 2. Avoids arbitrary code execution for installation. (Avoids setup.py)
> 4. Allows better caching for testing and continuous integration.
> 5. Creates .pyc files as part of installation to ensure they match the python interpreter used.
> 6. More consistent installs across platforms and machines.

But, let's be honest, it's the first and last points that are actually why I care about wheels. When you have wheel installed when you are installing packages, it builds a wheel for you so that it can reuse it in future installs. So, by uploading a wheel from the beginning, you are skipping that process and just using the precompiled versions instead of having to generate them from the source.

As I said originally, not supporting them isn't _that much_ of an issue and it's not the end of the world.

Supporting the wheel format is as simple as installing wheel (`pip install wheel`) and generating the wheels when you go to upload your new release (`python setup.py bdist_wheel --universal upload`).

**Comment by niwinz** [comment]
Seems easy, I'll try to do it for next release and maybe for the current one.

**Comment by srinivasreddy** [comment]
safely closed? @niwinz

**Comment by kevin-brown** [comment]
No recent releases include Wheels, @srinivasreddy.

I'm not sure if there are plans to do so in the next release.

**Comment by niwinz** [comment]
Uploaded the wheel ;)
