### ISSUE TITLE
Accessing DB 0?

### ISSUE THREAD

**Issue by chavenor** [niwinz/django-redis#234]
How can I access the rest of the lower name spaces with django-redis?

```cache.keys("*")```  

Is only giving me the name space 1:1:TEST which is the key I put in via django-redis.   See image below that's the only name space that I'm able to access?

Any ideas? 

![only-box](https://cloud.githubusercontent.com/assets/1850981/22185385/3661c0b6-e0aa-11e6-861a-e0173e641c70.png)

**Comment by niwinz** [comment]
I'm not cleary understand your question, the `:1:` prefix is completly unrelated to db number. If you want to use db 0, just put it on the settings.
