### ISSUE TITLE
Django redis connection.hget format

### ISSUE THREAD

**Issue by hesamd** [niwinz/django-redis#246]
Hi,

We ran into an issue where `con.hget(serial_number, "token")` return value is byte in Python 3, is this a normal behavior since we have to use decode `con.hget(serial_number, "token").decode('utf-8') == token` for our string comparision.

Thanks

**Comment by niwinz** [comment]
I'm not clearly understand the issue, seems like it works as expected, because the `con` is just a `StrictRedis` object from `redis-py` package (nothing related directly to django-redis impl).
