### ISSUE TITLE
wrong number of arguments for 'set' command when using as session cache

### ISSUE THREAD

**Issue by vladcalin** [niwinz/django-redis#255]
I am getting the following error:
```
Exception Type:	ResponseError
Exception Value:	
wrong number of arguments for 'set' command
```
The line (from my application) that is causing the error is ``login(request, user)``

Python version: 3.6.0
Django version: 1.11.0
redis-py version: 2.10.5

**Comment by prokaktus** [comment]
Hi! I've tried to look into your issue, but I cannot reproduce it. May you attach stacktrace or/and test project?

**Comment by vladcalin** [comment]
I solved the problem by upgrading the redis server to version 3.2 .Before that I had installed the 2.4.6 version (pretty old) and the error was caused by the wring number of arguments for the redis ``set`` command.

Sorry about that, I missed the section from the documentation where it said what versions of redis are supported. I will close the issue now.
