### ISSUE TITLE
fakeredis doesn't work with get_redis_connection

### ISSUE THREAD

**Issue by schuyler1d** [niwinz/django-redis#260]
`'CLIENT_CLASS': 'fakeredis.FakeStrictRedis'` raises the error:
`This backend does not support this feature`

It's not clear to me why get_redis_connection requires a 'get_client' method from the client rather than just returning the client directly, but if it's important, then `__init__.py` should just give the client only when it doesn't have that attribute (or test for fakeredis?).

This shim works:
```
from fakeredis import FakeStrictRedis

class StupidRedis(FakeStrictRedis):
    def get_client(self, *args, **kwargs):
        return self
```
so I suppose you could also provide that shim for fakeredis specifically.

**Comment by niwinz** [comment]
the get client is required becuase the purpose of `get_redis_connection` is returning the raw redis client and not the internal instance of "client". I'm not using fake redis, so if you have a solution for that please, sumbit a PR.

**Comment by ostcar** [comment]
Then maybe this is a bug in the documentation, because what is written here does not work:
https://niwinz.github.io/django-redis/latest/#_testing_with_django_redis
