### ISSUE TITLE
Should clear issue FLUSHDB?

### ISSUE THREAD

**Issue by alexhayes** [niwinz/django-redis#264]
Currently [.clear()](https://github.com/niwinz/django-redis/blob/202e4c319d28128b7bd4197477a503421e48faa8/django_redis/client/default.py#L291) iterates over keys using `scan_iter` and then for each calls `delete` on the key.

For large caches this can generate many calls to redis when I believe a `FLUSHDB` would be a better option.

Is there a reason why the `scan_iter`/`delete` approach was taken or would a PR that implemented a `FLUSHDB` be welcomed?

**Comment by niwinz** [comment]
The PR is welcome ;)
