### ISSUE TITLE
django_redis auto cache pei-site?

### ISSUE THREAD

**Issue by pudgetutu** [niwinz/django-redis#297]
django version:1.11
djangp_redis version:4.8

I clear all MIDDLEWARE,but for my view,if i not add @never_cache for view,it can cache.

but now i just want cache for session,no cache for per-site.

thank u

**Comment by niwinz** [comment]
This is not related to django-redis. django redis is a cache backend for django, in the same way as others backends. If for some reason your django app caches something, seems like a problem in a configuration. django-redis does nothing as-is with django views and all http stuff of django.
