### ISSUE TITLE
Is it possible to clear the cache ?

### ISSUE THREAD

**Issue by stuaxo** [niwinz/django-redis#309]
I enabled django_redis for caching and am getting some strange caching issues - (old versions of templates showing).

Is there a way I can delete the cache to test this further ?

**Comment by illagrenan** [comment]
Yes, you can delete all cache keys:

> (...) Finally, **if you want to delete all the keys in the cache, use `cache.clear()`**. Be careful with this; `clear()` will remove everything from the cache, not just the keys set by your application. (...)

Ref: https://docs.djangoproject.com/en/dev/topics/cache/

Or you can use something like this: https://github.com/rdegges/django-clear-cache/blob/master/clear_cache/management/commands/clear_cache.py Another option is to flush keys directly in Redis (https://redis.io/commands/flushdb).

**Comment by stuaxo** [comment]
Thankyou, I will be trying django-clear-cache in my deploy.

I'm still not quite sure why old versions of the templates were coming through.

We're behind cloudfront, I we set the TTL there to 0, and that was always returning that the cache was missed.

Still, in various browsers or just plain cURL I was getting old versions of the pages.

I haven't set a timeout on my cache provided by django-redis, so I'll see if that will make a difference next.

**Comment by illagrenan** [comment]
(Correct) caching is a really complex and complicated problem. In my opinion, this has nothing to do with `django-redis` package.

**Comment by stuaxo** [comment]
This is all true, I'd like to rule out redis-cache ... as it's something I can get a handle on.

I've (probably) ruled out cloudfront
and definitely ruled out browser caching.

The other bits are sticky things in the middle.... tbh I'm pretty sure it's not going to be redis-cache, but I'll see (+ if I clear the cache on deploy, that might be enough to hide the problem - it's probably some combination of all these things).

I guess when redis-cache, caches templates, the key it uses is not just the template name, but includes some sort of checksum ?  - In which case it must be something else.

**Comment by niwinz** [comment]
Seems unrelated to django-redis.

**Comment by syamjith44** [comment]
how to deal with it, If it is browser cache..

**Comment by WisdomPill** [comment]
please have a look at `Cache-Control` and `Expires` headers, like described [here](https://docs.djangoproject.com/en/4.1/topics/cache/#the-per-view-cache).

In this case might even be better to use Mozilla source [Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) and [Expires](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires)
