### ISSUE TITLE
Setting the timeout using a named argument does not work

### ISSUE THREAD

**Issue by xbogdan** [niwinz/django-redis#323]
Setting a cache key like this `cache.set('foo', 'bar', timeout=10) ` does not work, if the timeout argument is skipped it works, `cache.set('foo', 'bar', 10)`.

Can't say it is a very important issue but I thought I should let you know.
The documentation example is using the `timeout` argument.
http://niwinz.github.io/django-redis/latest/#_infinite_timeout

```
In[8]: from django_redis import VERSION
In[9]: VERSION
Out[9]: 
(4, 9, 0)
In[10]: from django_redis import get_redis_connection
In[11]: x = get_redis_connection('default')
In[12]: x.set('foo', 'bar', timeout=10)
Traceback (most recent call last):
  File "/Users/bogdanboamfa/.virtualenvs/lb/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-b47a9eac621e>", line 1, in <module>
    x.set('foo', 'bar', timeout=10)
TypeError: set() got an unexpected keyword argument 'timeout'
```

**Comment by niwinz** [comment]
Seems a bug, ty.

**Comment by TheOldMop** [comment]
Get get_redis_connection return raw redis client from Redis lib. You should use:
``ex`` for seconds.
``px`` milliseconds.
