### ISSUE TITLE
`touch` method is unimplemented

### ISSUE THREAD

**Issue by dougkeen** [niwinz/django-redis#331]
Attempting to use the `touch` method introduced in Django 2.1 (as documented [here](https://docs.djangoproject.com/en/2.1/topics/cache/#basic-usage)) results in the base class raising a NotImplementedError:

`raise NotImplementedError('subclasses of BaseCache must provide a touch() method')`

**Comment by niwinz** [comment]
You are right, i'll try to imlement this on the next week.

**Comment by niwinz** [comment]
Merged and released 4.10.0
