### ISSUE TITLE
get_redis_connection() should support decode_responses kwarg

### ISSUE THREAD

**Issue by selwin** [niwinz/django-redis#332]
Do you think this is a good idea? :)

**Comment by niwinz** [comment]
Hmm can you explain better the use case?

**Comment by goupper** [comment]
you can do this:
`from django.core.cache import caches`
`cache1 = caches['default']`
`cache2 = caches['other']`
`cache1.get('key')`
`cache2.set('key', 'value', None)`

**Comment by meteozond** [comment]
The problem is that cache backend unpickles values by default, but StrictRedis doesn't. 

```python
In [1]: from django_redis import get_redis_connection  

In [2]: get_redis_connection().set("key", "value")                                                                                                                               
Out[2]: True

In [3]: get_redis_connection().get("key")                                                                                                                                        
Out[3]: b'value'
```

We can add `decode_responses` option, but it will break cache unpickling.

**Comment by FaizanFareed** [comment]
**Solution can be** 
decode the key 

 `key = get_redis_connection().get("key")   `
`print(key) `
`# b'post:id:56' `

`print(key.decode())`
`# 'post:id:56'`

**Comment by fdev** [comment]
This is the code and configuration I use to work around this issue.

**myapp/redis.py**

```python
import json

from django.core.serializers.json import DjangoJSONEncoder
from django_redis.pool import ConnectionFactory as Factory
from django_redis.serializers.base import BaseSerializer


class JSONSerializer(BaseSerializer):
    """
    The default JSON serializer of django-redis assumes `decode_responses`
    is disabled, and calls `decode()` and `encode()` on the value.
    This serializer does not.
    """

    def dumps(self, value):
        return json.dumps(value, cls=DjangoJSONEncoder)

    def loads(self, value):
        return json.loads(value)


class ConnectionFactory(Factory):
    """
    Custom ConnectionFactory that injects the decode_responses parameter.
    """

    def make_connection_params(self, url):
        kwargs = super().make_connection_params(url)
        kwargs["decode_responses"] = True
        return kwargs
```


**myapp/settings.py**

```python
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "REDIS_CLIENT_CLASS": "redis.client.StrictRedis",
            "REDIS_CLIENT_KWARGS": {"decode_responses": True},
            # Custom serializer
            "SERIALIZER": "myapp.redis.JSONSerializer",
        },
    }
}

# Custom connection factory
DJANGO_REDIS_CONNECTION_FACTORY = "myapp.redis.ConnectionFactory"
```

**Comment by saranglakare** [comment]
I am facing this problem with django-redis 4.11.0 / Django 1.11 / Python 3.7.

I added `"REDIS_CLIENT_KWARGS": {"decode_responses": True},` but I was still getting `bytes` response for stored `str` values.

Next I tried to override `ConnectionFactory` as show in the above answer and it worked! This indicates to me that `decode_responses` option passed to `REDIS_CLIENT_KWARGS` does not work. Any ideas why? I checked the `django-redis` code and it seems to be fine.

Also, I am not seeing any issue with the default serializer so I am not overriding it. Could it be because I am on older version still? Will I need to override the serializer when I upgrade to latest django-redis (once I move to newer Django)?

Thanks!

**Comment by saranglakare** [comment]
Found something relevant. It seems the `REDIS_CLIENT_KWARGS` is not working because 

> when using a connection pool, the decode_responses argument of StrictRedis is ignored and must be set on the ConnectionPool instead

See this thread: https://github.com/redis/redis-py/issues/910#issuecomment-395837502
