### ISSUE TITLE
Django Cache Prefix / Version

### ISSUE THREAD

**Issue by Jarch09** [niwinz/django-redis#337]
Django allows you to remove the default cache prefix / version and provide your own cache key function. This library is not fully compatible with that functionality.

We should make these changes... happy to make a PR if you'll give me permission:

from `django_redis/utils.py`
```
def original_key(self):
    key = self._key.rsplit(":", 1)[-1]
    return key

def default_reverse_key(key):
    return key.split(':', 2)[-1]
```

**Comment by niwinz** [comment]
Please make a PR and we discuss the changes here.
