### ISSUE TITLE
add() returns None instead of False

### ISSUE THREAD

**Issue by krisrp** [niwinz/django-redis#340]
The API for add() is supposed to return False if the key exists, but instead returns None.
I've made a quick fix + PR but you guys might want to add additional checks.

**Comment by jdufresne** [comment]
The relevant docs:

https://docs.djangoproject.com/en/2.1/topics/cache/#django.core.caches.cache.add

> If you need to know whether add() stored a value in the cache, you can check the return value. It will return True if the value was stored, False otherwise.

**Comment by terencehonles** [comment]
I looked at this and according to the [redis documentation](https://redis.io/commands/set#return-value) `nx=True` will be `None` if the key already exists. If this code is checking for `is True` rather than truthy the call should just be wrapped in `bool(...)`
