### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by jdufresne** [niwinz/django-redis#346]
Looks like recent PRs and commits aren't being tested on Travis CI. Perhaps it was turned off? Please consider enabling it to help ensure new contributions are bug free. Thanks.

**Comment by kevin-brown** [comment]
Travis CI appears to be running against the master branch as well as tags, so it's definitely enabled on Travis's side. It's possible that it needs to be reconfigured so it picks up pull requests as well.

Though looking at the most recent builds, it may have also been re-enabled during the past day or so.

**Comment by niwinz** [comment]
https://travis-ci.org/niwinz/django-redis/pull_requests pull requests seems like enabled also.

**Comment by jdufresne** [comment]
Looks like it is working again :slightly_smiling_face:
