### ISSUE TITLE
Remove dependency on django.utils.six [future]

### ISSUE THREAD

**Issue by jsocol** [niwinz/django-redis#369]
I noticed this in a build of [django-ratelimit](https://github.com/jsocol/django-ratelimit) that was running against Django master. In that branch, per [ticket #27753](https://code.djangoproject.com/ticket/27753), they've [removed](https://github.com/django/django/commit/41384812efe209c8295a50d78b45e0ffb2992436#diff-12d44f314c03ae6a931c93c1f0748d6a) the `django.utils.six` module.

Obviously it's not coming immediately and it's still there in 2.2b, but wanted to give a heads up!

**Comment by niwinz** [comment]
PR welcome

**Comment by jsocol** [comment]
Just to be clear, I don't actually use django-redis myself or plan on making a patch here. Maybe a good first issue for someone?

**Comment by claudep** [comment]
I guess this should come with the removal of Python 2 support, which seems to be the trend currently in many Django apps. @jsocol, what's your plan about this removal?

**Comment by claudep** [comment]
Or sorry, the question was obviously addressed to @niwinz.

**Comment by koshak01** [comment]
?????????? where?

**Comment by terencehonles** [comment]
This is the same as #397 and #388 and is fixed by #401

**Comment by peterbe** [comment]
I haven't actually tested master yet because I'm waiting for a release. But...
[This commit](https://github.com/niwinz/django-redis/pull/401/files) put `django.utils.six` in [this commit](https://github.com/niwinz/django-redis/commit/2481a1aaed6a48975464684c0b97ab8d0c7ea7b1) all references to `six` are entirely removed.

**Comment by peterbe** [comment]
So, can we close this and hope for a new release sometime soon?

**Comment by jdufresne** [comment]
Yes, this has been fixed on master. (Testing is welcome.) We're working on a new release, see #400.
