### ISSUE TITLE
Is it possible to use django-redis as DB session storage (not сache storage)?

### ISSUE THREAD

**Issue by VasiliyRusin** [niwinz/django-redis#372]
So I have configuration with two different servers with different django apps but same sessions (the second server use slave redis db). I would like to divide redis cache and redis sessions. Is it even possible in django-redis?

**Comment by niwinz** [comment]
Yes, it is documented in the Django documentation: https://docs.djangoproject.com/en/2.1/topics/http/sessions/#using-cached-sessions
