### ISSUE TITLE
Django 3 Error

### ISSUE THREAD

**Issue by nyssance** [niwinz/django-redis#388]
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': cannot import name 'six' from 'django.utils'

**Comment by nyssance** [comment]
https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis
django.utils.six - Remove usage of this vendored library or switch to six.

**Comment by hingston** [comment]
Also #397 Django 3 is about to be released. Could this be a priority?

**Comment by jdufresne** [comment]
Fixed on master, please test there. We're working on getting a new release out.

**Comment by hingston** [comment]
I can confirm the fix works. Is a release close?

**Comment by toniengelhardt** [comment]
...close?

**Comment by jdufresne** [comment]
django-redis 4.12.1 went out May 27, 2020.
