### ISSUE TITLE
Does django-redis support Django 2.2.x

### ISSUE THREAD

**Issue by ozanteoman** [niwinz/django-redis#392]
Hello , Does django-redis support Django 2.2.x , because i was looking changelogs and i saw that 

https://github.com/niwinz/django-redis/blob/master/CHANGES.txt

```
that Version 4.10.0
--------------

Date: 2018-10-19

- Add support and testing for Django 2.1 and Python 3.7. No actual code changes
  were required.
- Add support for redis-py 3.0.
- Add touch command.
```

Could you explain me , thanks.

**Comment by Jamim** [comment]
Hello @ozanteoman,

Despite `django-redis` [4.10.0](https://pypi.org/project/django-redis/4.10.0/) doesn't declare support for `Django` 2.2, it works well with the latest `Django` in my case.
Also, you can find that support is declared in the `master` branch already:
https://github.com/niwinz/django-redis/blob/master/setup.py#L39

Best regards!

**Comment by ozanteoman** [comment]
Thank you so much ! , i saw it
