### ISSUE TITLE
 django.utils.six remove

### ISSUE THREAD

**Issue by koshak01** [niwinz/django-redis#397]
`from django.utils import six

class CacheKey(six.text_type):
    """
    A stub string class that we can use to check if a key was created already.
    """
    def original_key(self):
        return self.rsplit(":", 1)[1]`

**Comment by koshak01** [comment]
django 3 not worked

**Comment by dhcn** [comment]
The Django3 will be released ,this question should be fixed.

**Comment by kravietz** [comment]
@niwinz Django 3 is now officially the new stable https://docs.djangoproject.com/en/3.0/releases/3.0/

**Comment by kravietz** [comment]
Just for reference https://github.com/niwinz/django-redis/pull/394

**Comment by terencehonles** [comment]
And an alternate to #394 which allows dropping `six` #401

**Comment by dimkoug** [comment]
Could not find backend 'django_redis.cache.RedisCache': cannot import name 'six'   in django 3

**Comment by ieshan** [comment]
Seems like #391 has been merged which should solve the issue, any idea when we can expect a release?

**Comment by jdufresne** [comment]
Thanks closing.

> any idea when we can expect a release?

I'm working on moving the project to Jazzband to facilitate the next release. Stay tuned.

**Comment by hingston** [comment]
In the interim could you do a prerelease with these changes?
