### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by campfireman** [niwinz/django-redis#404]
Django has dropped support for python 2, hence they have dropped the module django.utils.six

`Could not find backend 'django_redis.cache.RedisCache': cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.7/site-packages/django/utils/__init__.py)`

**Comment by jdufresne** [comment]
Thanks. This issue has already been fixed in master. See commits 2481a1aaed6a48975464684c0b97ab8d0c7ea7b1 and 2ab2f5647dc69a4bf1357380aabb7b479e878b00. Can you please test using that. We are working on getting this into a release.

**Comment by campfireman** [comment]
Thanks for the reply, I didn't dig deep enough to see that, sorry!

**Comment by mcauto** [comment]
When will it be released?
